do {
  call ext.simpleFunction()
} catch is ExternalCallError {
  // recover gracefully
}
